apiVersion: v1
kind: Service
metadata:
  name: plant-disease-classifier-service
spec:
  selector:
    app: plant-disease-classifier
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: NodePort
