name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t yuvraj151/plant-disease-classifier .

    - name: Push Docker image
      run: |
        docker push yuvraj151/plant-disease-classifier

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml
